### PR TITLE
Implementation of value_to_string for all param types

### PR DESCRIPTION
**Pull request by mboecker**

### CODE REVIEW

**Comment by berndbischl** [comment]
1) please dont overengineer stuff. short.flags needs to go. same goes for show.miss.values, these should always be displayed as NA.
(actually @jakob-r we even dicussed that these are not even valid any more)

2) 0 tests are added. please add tests

3) your branch seems to be in conflict

4) for untyped please do something better. maybe simply display the class. what you are doing is bad

**Comment by berndbischl** [comment]
have you also really read all of this here
https://github.com/mlr-org/paradox/issues/43

**Comment by mboecker** [comment]
I hope I fixed 1 2 and 4 with this commit, and I will add tests before this is merged.
I read the full issue, what are you referring to specifically?

**Comment by berndbischl** [comment]
just wait. it makes zero sense like this. @jakob-r

**Comment by berndbischl** [comment]
@mllg currently uses as_short_string, this seems to be enough for now

**Pull request closed without merging**
