### PR TITLE
work on readme (WIP)

### PR DESCRIPTION
**Pull request by jakob-r**
Not ready but feel free to work on it.

1) dictionaries have been removed - maybe show a way to solve similar problems without dictionary?
2) <s>trafo are still WIP I guess.</s>

### CODE REVIEW

**Comment by mb706** [comment]
I'm going to be working on this today.

**Comment by mb706** [comment]
I'd say I'm done here for now, please review

**Comment by mb706** [comment]
AppVeyor appears to fail because it uses an outdated checkmate version.

**Comment by berndbischl** [comment]
@mb706 have you pushed lost of html file and pics and so on?

**Pull request merged**
