### PR TITLE
ps() shortcut

### PR DESCRIPTION
**Pull request by mb706**
## See the [description here](https://github.com/mlr-org/paradox/blob/shortcuts/attic/paramset.md)

```r
ps(a = p_dbl(1, 10), b = p_fct(c("a", "b", "c")))
```
```r
ps(a = p_dbl(1, 10, trafo = function(x) x^2))
```
```r
ps(
  a = p_dbl(1, 10, requires = b %in% c("a", "b") && c == 1),
  b = p_fct(c("a", "b", "c")),
  c = p_int(1, 2)
)
```

### CODE REVIEW

**Comment by mb706** [comment]
functions are not yet exported, so you have to load_all()

**Comment by mllg** [comment]
I don't get why we can't use simple standard evaluation for this.

```r
ps = function(...) do.call(ParamSet$new, list(...))

p_int = function(id, ...) ParamInt$new(id, ...)
p_dbl = function(id, ...) ParamDbl$new(id, ...)
```

**Comment by mb706** [comment]
that wouldn't give us a shortcut for trafos or requirements

**Comment by mb706** [comment]
Now I also implemented the `tune()` things, took me 1.5 hours.
### Playing Around
```r
paramset <- ps(a = p_int(1, 10), b = p_uty())
paramset$values$a <- tune(4, 10)
paramset$tune_ps
#> <ParamSetCollection>
#>    id    class lower upper levels        default value
#> 1:  a ParamInt     4    10        <NoDefault[3]>      
paramset$values$a <- tune(c(4, 7))
paramset$tune_ps
#> <ParamSetCollection>
#>    id    class lower upper levels        default value
#> 1:  a ParamFct    NA    NA    4,7 <NoDefault[3]>      
#> Trafo is set.
generate_design_grid(paramset$tune_ps)$transpose()
#> [[1]]
#> [[1]]$a
#> [1] 4
#> 
#> 
#> [[2]]
#> [[2]]$a
#> [1] 7
```
### Learner ParamSet
```r
library("mlr3")
ll <- lrn("classif.rpart")
ll$param_set$values = list(
    minsplit = 10,
    cp = tune(),
    maxcompete = tune(p_dbl(0, log(10), trafo = function(x) round(exp(x)))),
    maxdepth = 15
)

ll$param_set$tune_ps
#> <ParamSetCollection>
#>            id    class lower    upper levels        default value
#> 1:         cp ParamDbl     0 1.000000                  0.01      
#> 2: maxcompete ParamDbl     0 2.302585        <NoDefault[3]>      
#> Trafo is set.
```
### let's get dangerous

The following tunes the ParamUty `regularization.factor`
through the parameters `reg.sepal`, `reg.petal`
which the user-supplied trafo turns into the desired vector form
```r
library("mlr3learners")
lr <- lrn("classif.ranger")
lr$param_set$values = list(
  mtry = 2,
  num.trees = tune(p_dbl(log(100), log(1000),
      trafo = function(x) round(exp(x)))),
  regularization.factor = tune(
    ps(
      reg.sepal = p_dbl(0, 1),
      reg.petal = p_dbl(0, 1),
      .extra_trafo = function(x, param_set) {
        list(regularization.factor =
          c(x$reg.sepal, x$reg.sepal, x$reg.petal, x$reg.petal))
      }
    )
  )
)
lr$param_set$tune_ps
#> <ParamSetCollection>
#>           id    class   lower    upper levels        default value
#> 1: num.trees ParamDbl 4.60517 6.907755        <NoDefault[3]>      
#> 2: reg.sepal ParamDbl 0.00000 1.000000        <NoDefault[3]>      
#> 3: reg.petal ParamDbl 0.00000 1.000000        <NoDefault[3]>      
#> Trafo is set.
generate_design_random(lr$param_set$tune_ps, 1)$transpose()
#> [[1]]
#> [[1]]$num.trees
#> [1] 106
#> 
#> [[1]]$regularization.factor
#> [1] 0.2755469 0.2755469 0.1804057 0.1804057
```
The idea is that the (auto)tuner would get `param_set$tune_ps` and do its magic.

The implementation isn't very pretty yet, we should discuss the UI before I put work into making the implementation nicer.

**Comment by mb706** [comment]
we could possibly have the `trafo` for integer parameters do the rounding implicitly, and just write `trafo = exp`

**Comment by mb706** [comment]
or export a `round_exp` function because it is used frequently

**Comment by pfistfl** [comment]
I like the approach in general, I am a little afraid we are slowly moving towards a very complicated system, where we have multiple things that do somewhat the same thing (here `Domain` and `ParamSet`). 

There are a few things I find weird but seem necessary from an API perspective

- How do we explain what a `Domain` does vs. what a `Param/ParamSet` does? It seems hard to distinguish from the outside.
  Is it possible to obscure the `Domain`, such that the user rarely or never sees a `Domain` as the result is always a `Param`? 
  
- In `ParamSet` we construct from a list of `Param_XXX`, where names are given via the `Params` "id"  while we now have this named list schema. It seems that this is necessary, but again, we introduce an additional way of specifying things.
 

Additionally, it seems vital, that we finally start auto-inferring dependencies from the `graph` in mlr3pipelines, this seems to make up large parts of the necessary code.

**Comment by mb706** [comment]
I am actually trying to de-emphasize the `Domain` thing as much as I can here, and the large part of the documentation spent on it is more internal use than the user. As far as the user is concerned, the whole thing is supposed to be used for short forms (what I've heard people call "sugar"), so the resulting objects should not be inspected or worked with. The user should only know that he can use 
```r
pars <- ps(x = p_int(0, 10), y = p_fct(c("a", "b", "c")))
```
and
```r
pars$values$x <- tune(p_fct(2, 4, 6))
```
I would argue this is similar to how we do the short forms in other places. E.g. what happens in `lrn("classif.rpart", maxdepth = 3, predict_type = "prob")` is also a bit complicated: It is an alternative to both `LearnerClassifRpart$new()` and `mlr_learners$get("classif.rpart")` that then goes on to set hyperparameters *and* object properties (`predict_type` is not a hyperparameter). Still, to use it you don't really need to know about `mlr_learners` or even R6 constructors.

**Comment by mb706** [comment]
To do:
- [ ] fix some bugs
- [ ] document for users
- [ ] document internals a little
- [ ] turn p_xxx functions into proper functions
- [ ] write tests

**Comment by mb706** [comment]
anyone got an idea why CI fails?

**Comment by mb706** [comment]
Had to turn `tune_ps` active binding into a method, because of the new `as.list()` for environment thing.

**Comment by mb706** [comment]
to do
- [ ] p_fct documentation part in details section
- [ ] see if crate() should go into mlr3misc
- [ ] title of ps() broken
- [ ] ps() documentation: see domain
- [ ] repair CI fails
then this can be merged

afterwards:
- [ ] write book chapter

**Pull request merged**
