### PR TITLE
Add option to get values with, without and only with TuneTokens

### PR DESCRIPTION
**Pull request by be-marc**
without is default so we do not have to change all Learner*

### CODE REVIEW

**Comment by mb706** [comment]
@berndbischl should a learner throw an error when `$train()` is called and there is a TuneToken in there? In that case this should probably have another option`"error"` or similar which does that.

**Comment by berndbischl** [comment]
> @berndbischl should a learner throw an error when `$train()` is called and there is a TuneToken in there?

i thought the engin call was there to discuss exactly that...? pls really make sure that we come to a consent conclusion during the call. 

i think it is cleaner to remove the tokens during the beginning of tuning from the paramset. 
an yes, in that case i would probably issue an error during training, if they are still in there.
i don't think we need an option for that?

**Comment by jakob-r** [comment]
I think you two are on the same page but just talking past each other:

1. there are no more tune tokens in the learner during tuning
2. we need a simple way to throw an error if train is called with tune tokens in the param_set$values

@mb706 was referring to point 2. and suggested that this is solved in the `$get_values()` method

**Comment by berndbischl** [comment]
> 1. there are no more tune tokens in the learner during tuning

good.


> 2\. we need a simple way to throw an error if train is called with tune tokens in the param_set$values

why not simply length(get_values(type = "token")>0)  then stop("foo") in the train call?

**Comment by jakob-r** [comment]
becasue we would have to do thin for every learner?

**Comment by berndbischl** [comment]
> because we would have to do this for every learner?

no, you do that in the top-level train? and after that "assert" you KNOW there can be no tokens left?

**Comment by jakob-r** [comment]
Another option would be to have a function in mlr3
```r
get_learner_param_values = function(learner) {
  if ( length(get_values(type = "token") > 0)  stop("foo") 
  vals = learner$param_set$get_values()
}
```

**Comment by berndbischl** [comment]
you simply disentangle the assert from the getter? that seems best?

**Comment by jakob-r** [comment]
> > because we would have to do this for every learner?
> 
> no, you do that in the top-level train? and after that "assert" you KNOW there can be no tokens left?

Ok this seems to be the best solution. Simply do in `Learner$train()`. We just have to check that no one overwrites this and that there are no instances where we don't have a funny class inheriting from Learner that wants to use tune tokens.

**Review by mb706 — APPROVED** [review]

**Comment by jakob-r** [comment]
You could add tests that return empty lists. Otherwise it looks good and can be merged.

**Pull request merged**
