### PR TITLE
TuneToken only valid inside tuning

### PR DESCRIPTION
**Pull request by mb706**

### CODE REVIEW

**Comment by mb706** [comment]
* Introduces `ParamSet$fixed_values` -- everything that is not a `TuneToken`.
* Accessing `get_values()` (which presumably happens when values are being queried by a learner) when there is a `TuneToken` in the values is an error

**Comment by berndbischl** [comment]
IMHO the docs are not clear enough here why get_values now raises an error if a TT is present

**Comment by berndbischl** [comment]
or what you should do instead

**Comment by jakob-r** [comment]
I think we might close this PR in favor for #324

**Pull request closed without merging**
