### PR TITLE
use stable qunif fun for dbl

### PR DESCRIPTION
**Pull request by jakob-r**
related issue: #272

was already solved "hacky" in commit e9dfe42

### CODE REVIEW

**Comment by berndbischl** [comment]
please wait here until we resolved this

**Comment by mllg** [comment]
What was the result of the discussion again?

**Comment by mb706** [comment]
against merging this, will say more when I have time

**Comment by mb706** [comment]
The `$lower` and `$upper` checks should accept some leeway; ideally they should even correct things that are marginally below / above the limit to exactly the limit. This is because we could have a
```r
learner_ps <- ParamSet$new(list(ParamDbl$new("x", 1, 10)))
tuning_ps <- ParamSet$new(list(ParamDbl$new("x", log(1), log(10))))
tuning_ps$trafo <- function(x, param_set) {
  x$x <- exp(x$x)
}
points_to_try <- generate_design_grid(tuning_ps, 2)$transpose()
```
Here the `points_to_try` value falls out of the bounds of `learner_ps$x`:
```r
points_to_try[[2]] > 10  # TRUE
```

**Comment by mb706** [comment]
(Maybe the fix in this PR could fix this specific case, but there could still be trafos that have rounding errors bringing values outside the range)

**Comment by jakob-r** [comment]
Two thoughts:

- There rarely is a lower bound of 0 that is actually included in the set right? Otherwise, it could be critical to reach -0.00000001. 
- If the user wants to allow x+0.0001 he should write it down. Also: Usually the grid is not created from the feasible space but from the search space which is often a true subset.
- Actually I don't care so much. We can also have the formula of this PR + the slightly increased feasible region.

**Comment by mb706** [comment]
> Usually the grid is not created from the feasible space but from the search space which is often a true subset.

but whenever the search space is the whole feasible set but with a transformation before this thing may happen.

> We can also have the formula of this PR + the slightly increased feasible region.

I'd be ok with this.

**Comment by mllg** [comment]
Having a more numerical stable qunif can't be wrong, merging here.

**Comment by mb706** [comment]
okay so we are not going with increased feasible region now? :-/

**Comment by berndbischl** [comment]
> okay so we are not going with increased feasible region now? :-/

open another clean issue for that pls. i think the change here made sense too

**Pull request merged**
