### PR TITLE
Fix deep_clone for python builtins

### PR DESCRIPTION
**Pull request by pfistfl**
Not perfectly sure whether we should be specifc here or general (check for class or use try)
see #276

### CODE REVIEW

**Comment by jakob-r** [comment]
It's rather specific code but would be fine for me. You could also inherit and make a `ParamSetWithPythonObjects` class for your package but this might then be tiresome to keep up to date if `private$.value` changes. What does @mb706 think?

**Comment by jakob-r** [comment]
@mb706 Can you elaborate why you wrote this line:
https://github.com/mlr-org/paradox/blob/6365e875c84c5414031641608d8819ca42872a90/R/ParamSet.R#L491
not with 
```r
 if (inherits(x, "R6") && !is.null(x$.__enclos_env__)) { 
```
Only if it's a R6 class we want to clone it, right? This change would make this PR obsolete.

**Comment by mb706** [comment]
this is how R6 itself does it

**Comment by mb706** [comment]
https://github.com/r-lib/R6/blob/8e0b3182cdcc5047343e9c590816578472ec9dfa/R/clone.R#L92

**Comment by mb706** [comment]
My thought is that doing something that deviates from the R6 default clone may give unexpected problems

**Comment by mb706** [comment]
It is possible to create R6 objects that are just environments, this is probably why they do it:
```r
> xx <- R6Class("test", class = FALSE)
> xx$new()
<environment: 0x5645eba3ef60>
> class(xx$new())
[1] "environment"
```

**Comment by mb706** [comment]
```r
!is.null(tryCatch(x$.__enclos_env__, error = function(e) NULL))
```
?

**Comment by jakob-r** [comment]
Looks fine. Thanks

**Pull request merged**
